### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by hamza6348** [futureshocked/RaspberryPi-FullStack#1]
I am following the tutorial 'RaspberryPi-FullStack'. When I run the lab_app_uwsgi.ini I get an Internal Server Error. The uwsgi log file is like this
`[pid: 1103|app: -1|req: -1/1] 192.168.10.12 () {38 vars in 650 bytes} [Tue Jun 20 23:38:40 2017] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---`
I am new to coding, what I think is that OS is not allowing the server to access the hello.py( Flask app). Please help!!!

**Comment by nickalanf** [comment]
I am getting the same issue with this course, did you resolve this?

**Comment by futureshocked** [comment]
Hi,

Can you please create a support ticket about this though txplore.com? Just go to the lecture where you are having the problem and click on the Help Desk tab.

Thank you,

Peter

_______________________________
Dr Peter Dalmaris
Tech Explorations
Electronics Education for Makers
Author of Maker Education Revolution

**Comment by smartbsd** [comment]
The error is due to the fact that within the lab_app_uwsgi.ini file the app is set to lab_app and it has to be hello.

I have spend at least an hour trying to figure it out and after reading and reading I saw that the app is actually called hello so by placing that name there problem solved.

change
app = lab_app

with
app = hello

Hope this helps.

**Comment by pragathoys** [comment]
Hello,

the **lab_app_uwsgi.ini** file has been corrected:

https://github.com/futureshocked/RaspberryPi-FullStack/blob/master/lab_app_uwsgi.ini

Regards
Ioannis
